### ISSUE TITLE
Links in `about` section in footer don't link correctly. 

### ISSUE THREAD

**Issue by lsminter** [eggheadio/egghead-next#1030] opened 2022-01-18 19:07 UTC
The links in the `about` section, right side in the footer, don't link correctly and I've done some digging. 

If a user is logged out, all of the links work correctly but if a user is logged in, they aren't. The issue comes from the `Pricing` link not being displayed when the user is logged in and the user is a member. The links get offset so that `Store` links to `Pricing`, `Support` links to `Store`, `Log Out` links to `support@egghead.io`, and there is no `Log Out` button. 

If I log out then log back in, the links are fixed but if I refresh the page they get messed up again. 

It works just fine when logged in locally. It's just messed up live.

**Comment by lsminter** [comment] 2022-01-26 21:24
Here is a loom I recorded with Zac on the issue: https://www.loom.com/share/ad983f9c13c844eb8c2f48111fa1dfc6

**Comment by zacjones93** [comment] 2022-01-26 21:27
Can't reproduce locally. The fact that the component renders 15+ times seems like an issue to investigate.

**Comment by DrShpongle** [comment] 2022-02-02 08:09
fixed via https://github.com/eggheadio/egghead-next/pull/1038

**Closed** 2022-02-02 08:09 UTC
Labels: bug
