### ISSUE TITLE
bug: a link from the search results lead to egghead.io

### ISSUE THREAD

**Issue by YonatanKra** [eggheadio/egghead-next#250] opened 2021-01-03 11:01 UTC
I've searched for one of my videos and clicked the link. I was referred to the old egghead website.

Link: https://next.egghead.io/s/javascript-profiling-a-nodejs-app-from-the-chrome-dev-tools

Steps I've taken:
1. Entered "yonatan kra" in the search bar
2. Looked around the results
3. Clicked the title of the wanted lesson
4. Redirected to egghead.io

**Comment by joelhooks** [comment] 2021-01-03 17:58
anything `/s` is going to forward to the “api domain” because it is reserved for a url shortener 

we’d originally used it in our naming convention for this site for search, but had to migrate to `/q`

https://share.getcloudapp.com/KoulNbZj

I recorded this to try and reproduce the issue and wasn’t able to. A screen recording would be useful.

**Comment by YonatanKra** [comment] 2021-01-03 18:46
@joelhooks - here's a recording: https://youtu.be/mGnB-L8AC28
One thing I didn't mention - I'm using `brave` as a browser. Might that be the issue?

**Comment by joelhooks** [comment] 2021-01-03 19:03
Looks like there is something up with a couple items in Algolia as this particular video is on Page 1 of the results with the proper link and ~4 videos have the `/s/*` path.

I'm closing this, as it's not related to this application, but we'll look into it.

![image](https://user-images.githubusercontent.com/86834/103486497-3ba3b000-4db3-11eb-95e8-1c76fa383555.png)

**Closed by joelhooks** 2021-01-03 19:03 UTC

**Comment by joelhooks** [comment] 2021-01-03 19:10
![image](https://user-images.githubusercontent.com/86834/103486676-53c7ff00-4db4-11eb-967c-82469b668a16.png)

**Comment by joelhooks** [comment] 2021-01-03 19:48
this felt like an indexing anomaly so I just scripted a little cleaner to remove the objects from Algolia:

```js
import algoliasearch from 'algoliasearch'

const client = algoliasearch(APP_ID, API_SECRET)
const index = client.initIndex(INDEX_NAME)

const filter = {
  hitsPerPage: 1200,
  facetFilters: [
    'type:-lesson',
    'type:-course',
    'type:-podcast',
    'type:-talk',
    'type:-playlist',
  ],
}

const results = await index.search('', filter)

const offensiveIds = results.hits
  .filter((hit) => hit.type === null)
  .map((hit) => hit.objectID)

console.log(offensiveIds)

await index.deleteObjects(offensiveIds)
```
