### ISSUE TITLE
[BUG]: I can see the footer twice

### ISSUE THREAD

**Issue by YonatanKra** [eggheadio/egghead-next#872] opened 2021-09-16 03:12 UTC
Here's a screenshot of what I see:
![image](https://user-images.githubusercontent.com/6459899/133543355-9613fe40-9bcc-4313-87d0-3c1c8393db04.png)
It happens on every page I visit.

**Comment by joelhooks** [comment] 2021-09-16 03:50
https://github.com/eggheadio/egghead-next/blob/main/src/components/app/layout.tsx#L12

This is the only place the footer is called outside of the search page (where it was added to fix a double rendering issue)

This is some issue with Next and only reported here once. Not able to reproduce it at all so not going to be able to fix it.

**Comment by DrShpongle** [comment] 2021-09-20 11:12
fixed with https://github.com/eggheadio/egghead-next/blob/main/src/components/app/layout.tsx#L12

**Closed by DrShpongle** 2021-09-20 11:12 UTC
